FROM node:18-alpine

WORKDIR /home/appuser/app

RUN addgroup -S appgroup && adduser -S -D -G appgroup appuser

RUN chown -R appuser:appgroup /home/appuser/app

USER appuser

COPY --chown=appuser:appgroup package.json package-lock.json ./

RUN npm i

COPY --chown=appuser:appgroup . .

RUN npx prisma generate --schema=./src/prisma/schema.prisma

CMD ["npm", "run", "startDev"]
