version: "3"

services:
  api:
    container_name: catalyst_api_dev
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: dev
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/home/appuser/app/src:ro # mount volume - read only
      - /app/node_modules # anonymous volume
  
  db:
    container_name: catalyst_db_dev
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data # named volume

volumes:
  pg_data:
